Iwan dev branch
BenjaminFrazer/bterm pull request #1
Opened 2024-09-17 10:45 UTC by IwanEvans13

My dev branch which contains the new header file.

2024-09-17 15:50 UTC, BenjaminFrazer requested changes
Remove this file. Perhaps add ".vscode" to the .gitignore file.

2024-09-17 16:29 UTC, BenjaminFrazer commented on Functions/Health_Checks.c
> +    if (nargs != 6);{ //6 arguments as the command takes up 1
maybe allow up to six. i.e. nargs <=6

2024-09-17 16:29 UTC, BenjaminFrazer commented on Functions/Health_Checks.c
should be re-named to "built_in_functions.h"

maybe move "echo" command in here as well.

2025-06-15 18:17 UTC, merged

2025-06-15 18:17 UTC, BenjaminFrazer commented
Merged into history branch for now so I can test! Cheers @IwanEvans13.

2025-06-15 19:01 UTC, IwanEvans13 commented
This was the first branch i ever did back when i was playing around, it is NOT the history functionality and to be honest i have no idea what i actually did in the code, so i would not trust it. Sorry for the confusion, real history code has been pushed now. (If possible probs best to revert whatever code came from this, i doubt it could have been anything bad but better safe than sorry)

2025-06-15 20:12 UTC, BenjaminFrazer commented
Merged into history branch for now so I can test! Cheers @IwanEvans13.

2025-06-15 20:14 UTC, BenjaminFrazer commented
no worries, I didn't merge it into main haha.